### ISSUE TITLE
UtopiaIRC dependency broken

### ISSUE THREAD

**Issue by globalqss** [notifico/notifico#124]
Hello, found this error when running:
```
# python -m notifico init
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/notifico/notifico/__main__.py", line 21, in <module>
    from notifico.bots import start_manager
  File "notifico/bots/__init__.py", line 10, in <module>
    from notifico.bots.manager import BotManager
  File "notifico/bots/manager.py", line 7, in <module>
    from utopia import signals
ImportError: cannot import name signals
```

The next patch solved my problem:

```
diff --git a/setup.py b/setup.py
index f761e0e..b1f26d1 100644
--- a/setup.py
+++ b/setup.py
@@ -34,7 +34,7 @@ if __name__ == '__main__':
             'Flask-Cache',
             'fabric',
             'sqlalchemy',
-            'UtopiaIRC',
+            'utopia',
             'gevent',
             'oauth2',
             'redis',
@@ -49,6 +49,6 @@ if __name__ == '__main__':
             'celery'
         ],
         dependency_links=[
-            'https://github.com/TkTech/utopia/tarball/deploy#egg=UtopiaIRC'
+            'https://github.com/notifico/utopia/tarball/master#egg=utopia'
         ]
     )
```

Regards,

Carlos Ruiz
http://wiki.idempiere.org/en/User:CarlosRuiz

**Comment by Dav1dde** [comment]
Thanks, this is an issue introduced with #120, lgtm :+1:
